language: python
python:
  - "3.5"
  - "3.6"
services:
- postgresql

before_script:
- psql -c 'CREATE DATABASE test_db;' -U postgres  
install:
  - pip install -r requirements.txt
script:
  - pytest --cov=app
after_success: coveralls